### ISSUE TITLE
afw interface change: Calib to PhotoCalib

### ISSUE THREAD

**Issue by heather999** [LSSTDESC/gcr-catalogs#327] opened 2019-06-13 15:46 UTC
https://github.com/LSSTDESC/gcr-catalogs/blob/5203d46d6080f43d64657e0a47f499c77f71fb06/GCRCatalogs/butler_interface.py#L9
This line, likely needs to be:
```from lsst.afw.image import PhotoCalib```
This change occurred in April and is included in more recent releases of the DMstack, such as `w_2019_19` https://github.com/lsst/afw/commit/426a08a0d4216c860dd582c1ced7dc1dd3c47c9b

**Comment by yymao** [comment] 2019-06-13 15:53
Thanks, @heather999. I am closing this as it's duplicate of #283.

**Closed by yymao** 2019-06-13 15:53 UTC
Labels: duplicate
