### ISSUE TITLE
Fix units for I[xx,yy,xy] and friends in Object Table

### ISSUE THREAD

**Issue by wmwv** [LSSTDESC/gcr-catalogs#397] opened 2019-10-10 15:12 UTC
The second moments should be in arcseconds^2.  They're currently in pixels.

Multiple by pixel_scale^2 to correct.

**Comment by rmjarvis** [comment] 2019-10-10 16:48
I'm not sure how much it makes sense to just multiply these by pixel_scale**2.  These are fundamentally image quantities, not sky quantities.  I.e. x is in the pixel x direction.  Not, say, the direction along lines of dec or some other sky-related quantity.

If you wanted to convert to sky coordinates, the right thing to do is really

[ Iuu Iuv ] = [ du/dx  du/dy ]  [ Ixx Ixy ]  [ du/dx  du/dy ]^T
[ Iuv Ivv ]     [ dv/dx  dv/du ]  [ Ixy Iyy ]  [ dv/dx  dv/dy ]

where that first term, aka J, is the local Jacobian of the WCS transformation.  

This will generically include a rotation, a distortion, and a scaling.  The effect of the scaling is close to pixel_scale**2.  But I don't know that it makes sense to ignore the other three degrees of freedom (distortion is 2).  Nor for that matter to use an average pixel_scale for the arcsec/pixel scaling of all objects in the exposure.

I'm concerned that if people really want to study properties of the image, then they will be confused by getting arcsec rather than pixels.

I recommend leaving these as they are, and potentially adding new values in sky coordinates.  Either all three Iuu, Iuv, and Ivv if you can get the local Jacobian correct.  Or T = (Ixx + Iyy) * pixel_scale**2, either with the correct local pixel scale or the average pixel scale of the exposure, documented in either case which you choose.

**Comment by wmwv** [comment] 2019-10-10 17:09
Yeah, those are good points.  I agree that it's not clear what this should be.  It is presently a quantity in the DPDD that's defined to be in arcseconds.  I filed the following Project JIRA issue a while back about these issues.  There hasn't been a clear resolution.

https://jira.lsstcorp.org/browse/DM-19519

**Comment by wmwv** [comment] 2019-10-10 17:09
@rmjarvis Is one interpretation of your current recommendation as perhaps _removing_ I{xx,yy,xy} and replacing with a I{xx,yy,xy}_pixels set of column names?

**Comment by rmjarvis** [comment] 2019-10-10 17:13
That would be fine I think.  Explicit is better than implicit.  :)

It's not a crazy thing to want T_arcsec = (Ixx_pixels + Iyy_pixels) * pixel_scale**2 though.  So I might recommend adding that while you're at it.

**Comment by rmandelb** [comment] 2019-10-10 19:00
Speaking as somebody who regularly works with both the Ixx (etc.) quantities, and with PSF FWHM, I can confirm that Mike's logic is what leads me to expect Ixx (etc.) will be in pixels.  (I would find having them in arcsec confusing/surprising, and would assume you had done the proper calculation with the Jacobian that Mike mentioned.)  

In contrast I'm fine with PSF FWHM in arcsec.

I'm also happy with making things explicit.

**Comment by yymao** [comment] 2020-01-30 00:03
@wmwv I think we should get this fixed --- should we reassign this task to someone else?

**Comment by yymao** [comment] 2020-12-03 16:56
I'd like to sort out this issue before the public release :slightly_smiling_face: 

### Current status

I[xx,yy,xy] are in pixels. According to @rmjarvis and @rmandelb, this choice is in fact conventional and expected. However, @wmwv was correct to create this issue because in the DPDD ([LSE-163](https://lse-163.lsst.io/); p.45. See also https://jira.lsstcorp.org/browse/DM-19519), I[xx,yy,xy]  are defined in arcsec, which we are supposed to follow:

![image](https://user-images.githubusercontent.com/3792659/101060260-39a0c400-355d-11eb-82df-da329e9faca2.png)

### Possible resolutions:

- (A) Change I[xx,yy,xy] to be in arcsec, and create I[xx,yy,xy]_pixels that are in pixels.
- (B) Remove I[xx,yy,xy], and create I[xx,yy,xy]_pixels that are in pixels.
- (C) Do nothing. Keep I[xx,yy,xy] in pixels, ignoring DPDD. 

@wmwv proposed (B) and it seems people agree. The option is not 100% backward compatible but should not be too problematic. I want to confirm with experts here to see if there's further comment on these options.

**Comment by rmjarvis** [comment] 2020-12-04 16:23
FWIW, I think A and B are both acceptable, although I prefer B.

In fact my full preference would be B coupled with adding Iuu, Iuv, Ivv in arcsec.  (Or possibly call them Iuu_arcsec, etc.) 
These should be in actual sky coordinates with +u = west and +v = north according to the wcs.  But I don't know if there is sufficient information in the catalog currently to produce them. (Since it needs the local wcs.)

**Comment by wmwv** [comment] 2020-12-11 15:55
I vote that we do (B) now: Rename `I[xx,xy,yy]` to `I[xx,xy,yy]_pixels`.

and plan to do `I[uu,uv,vv]` in the future.

(Thanks to @yymao for helpfully prompting me to pay attention to this)

**Comment by wmwv** [comment] 2020-12-11 16:19
Hmmm... one more question.  `I[xx,xy,yy]PSF` is in arcseconds.  Should we
1. Keep `I[xx,xy,yy]PSF` as is [in arcseconds]
2. Rename `I[xx,xy,yy]PSF` to `I[xx,xy,yy]PSF_arcsec`

**Comment by rmjarvis** [comment] 2020-12-11 16:33
I would suggest whenever you have any moments in x,y coordinates (i.e. pixel, not sky) then they should be in pixels.  Whenever you have them in u,v coordinates (local sky coordinates with north up) then they should be in arcsec.

**Comment by yymao** [comment] 2020-12-11 19:37
So I guess we should do
- Remove `I[xx,xy,yy]PSF`, add `I[xx,xy,yy]PSF_pixel`

@wmwv agree? 

BTW I think we can use `I[xx,xy,yy]_pixel` instead of `I[xx,xy,yy]_pixels`.

**Comment by wmwv** [comment] 2020-12-11 20:58
> BTW I think we can use I[xx,xy,yy]_pixel instead of I[xx,xy,yy]_pixels.

Oh, yes.  Agreed on singular.

**Comment by wmwv** [comment] 2020-12-11 21:00
> I would suggest whenever you have any moments in x,y coordinates (i.e. pixel, not sky) then they should be in pixels. Whenever you have them in u,v coordinates (local sky coordinates with north up) then they should be in arcsec.

Thank you.  That's very clear and reasonable.

**Closed** 2020-12-23 23:41 UTC
Labels: bug, dpdd-catalog, help wanted, priority:high, reader, schema
